### ISSUE TITLE
API MD5 authentication is insecure.

### ISSUE THREAD

**Issue by lvella** [coinexcom/coinex_exchange_api#11]
It seems the secret key is not transmitted alongside the message as an extra security layer, in case of breach of SSL. But by itself, authenticating the message with a plain MD5(message + key) is insecure, as explained in [HMAC Wikipedia page](https://en.wikipedia.org/wiki/HMAC#Design_principles). I recommend to deprecate such method for new keys, and use instead HMAC or maybe SHA-3, which can be used in place of MD5 in this case (SHA-3 doesn't suffer from the vulnerability).

It is also a hassle to have to reencode a JSON message in ordered GET format, it would be much easier if I could generate the authorization code directly from the JSON data sent.

**Comment by lvella** [comment]
I found that [BLAKE2](https://tools.ietf.org/html/rfc7693) is a very good choice for authentication. It is much faster than SHA-3 on CPU and has a `key` parameter, where the secret key can be passed directly.

**Comment by pandyer** [comment]
签名 用okex 的方法通用.  交流QQ: 592801 量化交易
