### ISSUE TITLE
How to subscribe multiple depth pairs via websocket?

### ISSUE THREAD

**Issue by Andytreee** [coinexcom/coinex_exchange_api#14]
How to subscribe multiple depth pairs? I  want to  subscribe   BTC/USDT   CET/USDT pairs, but when  i sent twice , the previous one will be replaced. 
{
  "method":"depth.subscribe",
  "params":[
    "BTCUSDT",               #1.market: See<API invocation description·market> 
    5,                      #2.limit: Count limit
    "0"                     #3.interval: Merge，String
  ],
  "id":15
}

**Comment by schmidt77** [comment]
Hi! You have to open multiple websocket connections - for each market one connections.

**Comment by haipome** [comment]
no limit

**Comment by haipome** [comment]
We will fix this on V2 Api in the future.

**Comment by zimmiBTC** [comment]
What is the ETA for v2 ?
