### ISSUE TITLE
order is missing in trade data

### ISSUE THREAD

**Issue by khoan** [coinexcom/coinex_exchange_api#15]
I note down order details every time I place an order.

As of 29 June 2018, https://github.com/coinexcom/coinex_exchange_api/wiki/039user_deals documents in **Return value description** that **id** is **order number**. However, I cannot lookup order in my system with such **id**.

Please advise.

**Comment by schmidt77** [comment]
I guess that **id** is probably not the Order-ID, but the Deal-ID.

**Comment by haipome** [comment]
Sorry for the missing, we will add the order id soon.

**Comment by buyongji** [comment]
https://github.com/coinexcom/coinex_exchange_api/wiki/039user_deals
added.
