### ISSUE TITLE
withdraw 提币问题

### ISSUE THREAD

**Issue by djy** [coinexcom/coinex_exchange_api#16]
https://github.com/coinexcom/coinex_exchange_api/wiki/062submit_withdraw

提交一个提币order。
其中参数：coin_address
描述：use ":" to put “address” and “payment_id” 

payment_id那里来呢？

**Comment by djy** [comment]
是否支持内部 手机或者邮箱提币呢

**Comment by dizlehfk** [comment]
:"0x83cef37ae0ce0883e59225793f9c2b1889e1a1d8"sonic080807@naver.com

**Comment by buyongji** [comment]
提现XMR、XMC、XMV时，如果有payment_id,需要拼接在地址后面。如果不需要填写payment_id，则不用填写。

**Comment by djy** [comment]
请问是否支持内部提币呢？内部的CET的内部转账。网页端是可以的。api是否支持？
