### ISSUE TITLE
I get a 404 when trying to get my exchange balance through the API

### ISSUE THREAD

**Issue by priestc** [coinexcom/coinex_exchange_api#2]
Here is the code I'm using to make the request:

    def _auth_request(self, url, params=None):
        params['tonce'] = make_standard_nonce()
        params['access_id'] = self.access_id
        str_params = urlencode(sorted(params.items(), key=lambda x: x[0])) #alphabetize
        to_sign = str_params + "&secret_key=%s" % self.api_secret
        digest = hashlib.md5(to_sign).hexdigest().upper()
        return self.get_url(url + str_params, headers={
            'Content-Type': 'application/json',
            'authorization': digest})

    def get_exchange_balance(self, crypto):
        url = "https://api.coinex.com/v1/balance/"
        resp = self._auth_request(url, {}).json()
        return resp

The url being hit is: https://api.coinex.com/v1/balance/access_id=CBC91...&tonce=1514650947531

and the signature is D7B19280DF3C4A1E25AAA461F83214DB

what could I be doing wrong?

**Comment by buyongji** [comment]
the url is not right.
https://api.coinex.com/v1/balance?access_id=CBC91...&tonce=1514650947531
