### ISSUE TITLE
market depth goes out of sync

### ISSUE THREAD

**Issue by algotek** [coinexcom/coinex_exchange_api#20]
On fast price movement the order book seems like goes out of sync.
Is there a code example (preferably c#) that shows how to maintain the order book?

**Comment by schmidt77** [comment]
Did you use WebSockets or the HTTP Endpoints? I did some tests and noticed, that Websockets are updated later compared to response of HTTP endpoint. Thus I'm polling the HTTP endpoint instead of subscribing the WebSocket.

**Comment by algotek** [comment]
The websocket has incremental update which goes out of sync on fast movement, except if I do not understand the rules there, thats why it would be good to see an example.

**Comment by schmidt77** [comment]
Try to re-subscribe every x minutes/seconds, than you should get full and up-to-date orderbook.

**Comment by algotek** [comment]
If you do not understand the question maybe do not comment
