### ISSUE TITLE
ID verification is no response

### ISSUE THREAD

**Issue by motodmax** [coinexcom/coinex_exchange_api#23]
I sent ID verification on websocket.
but server sent no response and websocket immediately closed.

**Comment by jscrapy** [comment]
me too

**Comment by bsliran** [comment]
Same happens to me
is there any estimate for a fix?

**Comment by ronenkag** [comment]
getting unknown error code 11 when I sent ID verification on websocket... no responses yet?

**Comment by buyongji** [comment]
This issue has been resolved and the documentation has been updated.
https://github.com/coinexcom/coinex_exchange_api/wiki/050id_verification

**Comment by ronenkag** [comment]
If the only change was from object {} to array [], it didn't fix the issue, still having error code 11

"params": {} ->
"params": [
    "4DA36FFC61334695A66F8D29020EB589",
    "C6F0DDA352101C2258F992A277397F4A", #sign data 
    1513746038205  #for milliseconds spent from Unix epoch to current time and error between tonce and server time can not exceed plus or minus 60s
  ], - didn't help

**Comment by motodmax** [comment]
Thank you!
I tried this API now.
It's FIne!
