### ISSUE TITLE
Get wallet deposit address via API

### ISSUE THREAD

**Issue by alecdhuse** [coinexcom/coinex_exchange_api#25]
Can you please implement an API call to get the deposit address for a given currency?

**Comment by Hachi2018** [comment]
Thank You

**Comment by haipome** [comment]
@buyongji

**Comment by w7788129** [comment]
😀

**Comment by kyawswarlinn1994** [comment]
Good

**Comment by saikatharryc** [comment]
Hi, @haipome  , @buyongji  any update on this?
need api for get/create  deposit address

**Comment by jsyzlb5255** [comment]
I'm proud of you !
