### ISSUE TITLE
取消订单问题

### ISSUE THREAD

**Issue by ezencart** [coinexcom/coinex_exchange_api#26]
`	$requestdata=array(
		'market'=>'LOOMBCH',
		'id'=>'934131734',
	);
	echo $sell_respond=curlPost('order/pending',$apikey['A'],'get',$requestdata);	`

返回
`{
  "code": 0, 
  "data": {
    "count": 1, 
    "curr_page": 1, 
    "data": [
      {
        "amount": "10", 
        "asset_fee": "0", 
        "avg_price": "0.00", 
        "create_time": 1531241329, 
        "deal_amount": "0", 
        "deal_fee": "0", 
        "deal_money": "0", 
        "fee_asset": null, 
        "fee_discount": "0", 
        "id": 934131734, 
        "left": "10", 
        "maker_fee_rate": "0.001", 
        "market": "LOOMBCH", 
        "order_type": "limit", 
        "price": "0.00031497", 
        "status": "not_deal", 
        "taker_fee_rate": "0.001", 
        "type": "sell"
      }
    ], 
    "has_next": false
  }, 
  "message": "Ok"
}`

access_id tonce参数每个请求都会用到，写到函数公共部分， 每次请求都头信息都签名了

但实际订单没有取消

**Comment by Hachi2018** [comment]
Thank You

**Comment by jscrapy** [comment]
me too

**Comment by buyongji** [comment]
删除订单是用DELETE请求

**Comment by ezencart** [comment]
@buyongji 

 	$requestdata=array(
		'market'=>'LOOMBCH',
		'id'=>'1008134441',
	);	

	$sell_respond=curlPost('order/pending',$apikey['A'],'delete',$requestdata);	
	$sell_respond_array=json_decode($sell_respond,true);

返回

Array
(
    [message] => Array
        (
            [id] => Missing required parameter in the query string
            [market] => Missing required parameter in the query string
        )

)

就剩下删除订单的， 其他请求都在正常的 删除订单的四个产生 id market access_id tonce 都发送了， 怎么返回还缺少参数
