### ISSUE TITLE
Support multi markets data in market depth websocket api.

### ISSUE THREAD

**Issue by lovishvadh** [coinexcom/coinex_exchange_api#29]

**Comment by Hydrorastaman** [comment]
Or don't automatically unsubscribe from previous instrument on new market depth subscription.

**Comment by haipome** [comment]
We will fix this on the V2 API in the future.

**Comment by zimmiBTC** [comment]
is there an ETA for v2 ?

**Comment by Hydrorastaman** [comment]
@zimmiBTC  workaround for this issue: create one connection per instrument for L2 data and send ping frame each minute.
