### ISSUE TITLE
withdrawal bug when using balance/coin/withdraw

### ISSUE THREAD

**Issue by zimmiBTC** [coinexcom/coinex_exchange_api#30]
https://github.com/coinexcom/coinex_exchange_api/wiki/062submit_withdraw

Sometimes works, but often I get a "Invalid withdrawal address" error message when the withdrawal address is just fine (if works using the web GUI.

**Comment by buyongji** [comment]
you must add  address to white list.https://www.coinex.com/apikey.

**Comment by kendol07** [comment]
> Debe agregar la dirección a la lista blanca. https://www.coinex.com/apikey .

I want to be able to withdraw to any currency address without having to be approved on the Coinex platform

**Comment by ifernandm** [comment]
tnx ccxt team for very useful and easy api.
not way for withdrawl with api without whitelist or add whitelistautomatically ?
if whitelist required,, auto withdrawl not usefull.!!

**Comment by mahdi4187** [comment]
This api has no use and is the same as the manual mode. In general, if it is to be added to the white list every time, we will do it manually.

**Comment by mentorvid** [comment]
i have the same problem
