### ISSUE TITLE
Unknown error code 11 when trying to authorize to web socket trading API

### ISSUE THREAD

**Issue by ronenkag** [coinexcom/coinex_exchange_api#31]
trading_stream.call('server.sign', login_params).then(
                    ()=>{ ... }
                ).catch((e)=>{
                    // getting here with e = {"code": 11}
                });

**Comment by buyongji** [comment]
This issue has been resolved and the documentation has been updated.https://github.com/coinexcom/coinex_exchange_api/wiki/050id_verification。
