### ISSUE TITLE
WebSocket trade API ID not working

### ISSUE THREAD

**Issue by zimmiBTC** [coinexcom/coinex_exchange_api#33]
It now always returns:
message '{"error": {"code": 11, "message": "IP:172.31.20.161 is not allowed"}, "result": null, "id": 115}'

Problem is that this is not my IP address, and it returns this error no matter where I try it from.

I have my IP address enabled on the API key I am using, so that is not the issue.

**Comment by ronenkag** [comment]
Having the same issue with websocket connection, getting error code 11

**Comment by ronenkag** [comment]
now it's fixed

**Comment by buyongji** [comment]
had fixed
