### ISSUE TITLE
订阅多个交易对k线

### ISSUE THREAD

**Issue by li-hu** [coinexcom/coinex_exchange_api#34]
我试过使用 : 
{ "id": 0, "method": "kline.subscribe", "params": ["TRXETH", "CARDBTC", "CETETH", "EOSDACBCH",1] }
或者
{"method": "kline.subscribe","params": [["TRXETH",1],["CARDBTC",1],["CETETH",1],["EOSDACBCH",1]],"id": 0}
都是返回非法参数.  是我的请求方式有问题还是不支持订阅多个交易对K线?

**Comment by numjung1959** [comment]
Hoo

**Comment by buyongji** [comment]
Not support mulit-market in websocket subscription.
