### ISSUE TITLE
Desperately Need Access to Account History Including Gifts, Deposits and Withdrawals

### ISSUE THREAD

**Issue by joemccann** [coinexcom/coinex_exchange_api#35]
From the website, I am able to view the history of assets including their gifts here:

https://www.coinex.com/res/account/balance/history?start_time=1530946800&end_time=1531638000&asset=CARD&limit=10&page=1

But there is no API for this. 

Will this be available soon?

**Comment by lhl** [comment]
Watching this as I'm also keen to be able to track/import gifts and other distributions into my accounting system...

**Comment by lhl** [comment]
btw any coinex peeps actually watching these issues, (like @buyongji?)
