### ISSUE TITLE
Acquire Latest Transaction Data - last_id parameter not working

### ISSUE THREAD

**Issue by algotek** [coinexcom/coinex_exchange_api#38]
The last_id is ignored, only the last 1000 trade is returned.
Example call:
https://api.coinex.com/v1/market/deals?market=BTCUSDT&last_id=377867782

Please fix last_id and also add last_date parameter, which can request older data by date.

**Comment by ohenrik** [comment]
Would really appreciate if this gets fixed. At the moment it is impossible to get trade history from you.
