### ISSUE TITLE
"code": 227, "message": "tonce check error, correct tonce should be within one minute of the current time"

### ISSUE THREAD

**Issue by mvpigmax** [coinexcom/coinex_exchange_api#4]
when i use your demo, get_account() appear error as follow:

"code": 227, "message": "tonce check error, correct tonce should be within one minute of the current time"

and the code print tonce is bellow:
my post 'tonce': 1518009608459

 why appear this error message?

**Comment by mvpigmax** [comment]
< 
   def set_authorization(self, params):
        params['access_id'] = self.access_id
        params['tonce'] = int(time.time() * 1000)
        self.headers['AUTHORIZATION'] = self.get_sign(params, self.secret_key)
>

**Comment by mvpigmax** [comment]
<    def set_authorization(self, params):
        params['access_id'] = self.access_id
        params['tonce'] = int(time.time() * 1000)
        self.headers['AUTHORIZATION'] = self.get_sign(params, self.secret_key)>

**Comment by mvpigmax** [comment]
def set_authorization(self, params):
        params['access_id'] = self.access_id
        params['tonce'] = int(time.time() * 1000)
        self.headers['AUTHORIZATION'] = self.get_sign(params, self.secret_key)

**Comment by mvpigmax** [comment]
i got it
your local systime is above mine.
i suggest you check your local time

**Comment by liudy2162** [comment]
still have problem like this ,help !
