### ISSUE TITLE
There needs to be a way to query all open orders

### ISSUE THREAD

**Issue by EchterAgo** [coinexcom/coinex_exchange_api#41]
The current API makes you iterate over all possible markets to get all open orders. This can be quite inefficient if you have orders on many markets. v1/order/pending should make the market parameter optional and when it is not specified it should return all the pending orders.

**Comment by schmidt77** [comment]
Any news on this?

**Comment by EchterAgo** [comment]
They still haven't added anything about this to the API docs, so likely no.
