### ISSUE TITLE
Websocket kline query returns 'Invalid parameter'

### ISSUE THREAD

**Issue by JKorf** [coinexcom/coinex_exchange_api#46]
I've been able to use all websocket methods just fine, however I cant seem to get querying kline data to work.
I'm sending `{"method":"kline.query","params":["BTCBCH",60],"id":2}` as per documentation, but I always get `invalid argument` as an answer. I tried changing both the market string and the seconds parameter but no luck. Anyone knows what the problem is?

**Comment by mato1ch** [comment]
Still does not work as should
