### ISSUE TITLE
POST signature errors

### ISSUE THREAD

**Issue by mscheetz** [coinexcom/coinex_exchange_api#47]
When sending POST requests (Orders, Withdrawal requests) am i supposed to be signing the whole request body? 
# Request
POST https://api.coinex.com/v1/order/limit
# Request.Body
{
  "access_id":" BFFA64957AA240F6BBEA26F4E07EC0D9",
  "amount": "56.5",  # order count
  "price": "10",   # order price
  "type": "sell",    # order type
  "market":"BTCBCH",  # market type
  "tonce": 1513746038205,
  "source_id": "123" # user defines number and return
}
or just sign
{
  "access_id":" BFFA64957AA240F6BBEA26F4E07EC0D9",
  "tonce": 1513746038205,
}
I'm getting this response on all my POSTs trying both ways:
{
  "code": 25,
  "data": {}
  "message": "Signature Error"
}

Any help is appreciated!

**Comment by SpyAlex** [comment]
Sort all parameters in alphabetic order.

**Comment by mscheetz** [comment]
I was adding 
```secretKey=XXXXXX```
not
```secret_key=XXXXX```
to my message to be signed
