### ISSUE TITLE
关于websocket API的两个问题

### ISSUE THREAD

**Issue by qidaneix** [coinexcom/coinex_exchange_api#48]
1. websocket的各接口文档中，都有两种方式：acquire以及subscribe，请问两者有何区别？websocket不都是订阅（websocket.send()）然后服务端主动推送信息（websocket.on('message', () => {})）吗？

2. 获取深度的websocket API（(https://github.com/coinexcom/coinex_exchange_api/wiki/044depth#subscribe-market-depth)[https://github.com/coinexcom/coinex_exchange_api/wiki/044depth#subscribe-market-depth]）,订阅消息中有交易对信息（BTCBCH），但服务器推送的消息中没有告诉我是那个交易对，我怎么区别返回的是哪个交易对的深度消息？
```
#Request

{
  "method":"depth.subscribe",
  "params":[
    "BTCBCH",               # 交易对
    5,  
    "0"  
  ],
  "id":15
}

#notify 没有告诉我是哪个交易对的深度信息
{
  "method": "depth.update", 
  "params": [
    false,                  #Boolean, true: for complete result，false: for update based on latest retrun result
    {                       #Update info
      "bids": [             #Depth of Buy
        [
          "12.25",          #Buy in price
          "0.0588"          #Buy in count
        ]
      ],
      "asks": [             #Depth of Sell
        [
          "12.94",          #Sell out price
          "0.1524"          #Sell out count
        ]
      ]
    }
  ], 
  "id": null
}
```

**Comment by echo-ray** [comment]
@qidaneix @buyongji @haipome 
1. 我理解acquire 跟其它交易所的req一样，只返回一次结果，sub才会持续的给客户端推。
2. 我今天试试在返回的“params”里有 交易对信息了。

另外想问一下，在同一个连接里可以订阅多个交易对吗？我这边似乎只返回最后订阅的那一个

**Comment by qidaneix** [comment]
@echo-ray 你的问题的结果其实也是我第二个问题的答案。
coinex订阅深度信息的websocket是一个交易对就要建立一个wss链接，无法在一个wss上订阅多个交易对信息，这和其他交易所差别很大（binance是一个wss订阅所有你想要的信息--|||），所以这么看的话，我提的第二个问题也就不是问题了，他不需要在推送消息中返回交易对标识。
