### ISSUE TITLE
error code 1, when placing limit order

### ISSUE THREAD

**Issue by seyrafi** [coinexcom/coinex_exchange_api#58]
I'm getting an unknown error when placing a limit order:
"{  "code": 1,   "data": {},   "message": "Data can not be serialized to json format"}"

**Comment by dinastyoffreedom** [comment]
I having some error.

**Comment by buyongji** [comment]
demo:
https://github.com/coinexcom/coinex_exchange_api
https://github.com/ccxt/ccxt
