### ISSUE TITLE
I am getting Signature error when calling the API for Inquire Account Info

### ISSUE THREAD

**Issue by FaizanNehal** [coinexcom/coinex_exchange_api#68]
When I am calling the API to test for my Account info according to https://github.com/coinexcom/coinex_exchange_api/wiki/060balance I am getting an Signature error in the response while the code is 25. Any idea how can I solve this?

**Comment by versionzhang** [comment]
Please check our demo code for your information. https://github.com/coinexcom/coinex_exchange_api
