### ISSUE TITLE
Question about the MD5 hash of signature string in request header

### ISSUE THREAD

**Issue by westerpants** [coinexcom/coinex_exchange_api#7]
In the example of this page
https://github.com/coinexcom/coinex_exchange_api/wiki/012security_authorization

The following string is hashed by MD5 algorithm
access_id=4DA36FFC61334695A66F8D29020EB589&amount=1.0&market=BTCBCH&price=680&tonce=1513746038205&type=buy&secret_key=B51068CF10B34E7789C374AB932696A05E0A629BE7BFC62F 

And the result is:
C6F0DDA352101C2258F992A277397F4A

but I have tried multiple times, my MD5 result is 
610AB90A1D31D45901D173E4F59C9384

For example I hash the string in https://passwordsgenerator.net/md5-hash-generator/, http://onlinemd5.com/, both give 610AB90A1D31D45901D173E4F59C9384 but not C6F0DDA352101C2258F992A277397F4A

Is there any issue with your example?

**Comment by pandyer** [comment]
签名 用okex 的方法通用. 交流QQ: 592801 量化交易
