### ISSUE TITLE
Can't Inquire Account Info Code 25

### ISSUE THREAD

**Issue by stero1** [coinexcom/coinex_exchange_api#70]
While enjoying Coinex app I'm having an authorization api issue with an error code 25 

I'm sending get requests to inquire account info following security invocation instructions but always returns signature error back.

> curl -H "Content-Type: application/json; charset=utf-8" -A "Chrome/39.0.2171.71" -H "authorization: B62CBE1226D4A657C0C7022976654F6F" --request GET https://api.coinex.com/v1/balance/info?access_id=XXXXXX&tonce=1617284260&secret_key=XXXXXX

tonce within 60 seconds deviation, encrypting full https request and uppercasing in to authorization header please point in to right direction.

**Comment by Hmaghsoumi** [comment]
I have this problem too.

**Comment by versionzhang** [comment]
Please check your generate authorization header function. You can view our demo code for your 
favorite code. https://github.com/coinexcom/coinex_exchange_api
