### ISSUE TITLE
Wrong wiki request url

### ISSUE THREAD

**Issue by Cregrant** [coinexcom/coinex_exchange_api#74]
We need to update the wiki, right? URL given by the page won't cancel all orders, only limit ones.
Page - https://github.com/coinexcom/coinex_exchange_api/wiki/0315cancel_all

Old request URL - https://api.coinex.com/v1/order/pending
Stop orders request URL - https://api.coinex.com/v1/order/stop/pending

I can get "_ {" code ": 0," data ": null," message ":" Success "} _" from both URLs, but the first one doesn't cancel any stop-orders.

**Comment by versionzhang** [comment]
https://api.coinex.com/v1/order/pending canceling your pending limit order.
https://api.coinex.com/v1/order/stop/pending canceling your stop pending limit order.
If you want to cancel all orders, you should call both api.
