### ISSUE TITLE
Mismatched wiki request url

### ISSUE THREAD

**Issue by mdahlin** [coinexcom/coinex_exchange_api#77]
For the [Place Multiple Limit Orders](https://github.com/coinexcom/coinex_exchange_api/wiki/0312limit_batch_orders) wiki page, the listed "Request Url" is different from the url in the example

 * "Request Url": https://api.coinex.com/v1/order/limit/batch
 * example url: https://api.coinex.com/v1/order/batchlimit

**Comment by versionzhang** [comment]
@mdahlin Thanks for your feedback, please use [https://api.coinex.com/v1/order/limit/batch](https://api.coinex.com/v1/order/limit/batch), I had fixed this error.
