### ISSUE TITLE
Acquire K-Line Data

### ISSUE THREAD

**Issue by kabiri** [coinexcom/coinex_exchange_api#81]
how convert time (data[0][0]) to datetime 
https://api.coinex.com/v1/market/kline?market=bchbtc&type=1min

# Response
{
  "code": 0,
  "data": [
    [
      1492358400, # Time  <------- This data
      "10.0",   # Opening
      "10.0",   # Closing
      "10.0",   # Highest
      "10.0",   # Lowest
      "10",     # Volume
      "100",    # amount
      "BCHBTC", # market
    ]
  ],
  "message": "Ok"
}

**Comment by versionzhang** [comment]
you can search convert "timestamp to datetime"
