### ISSUE TITLE
Wrong signature in examples

### ISSUE THREAD

**Issue by kalgecin** [coinexcom/coinex_exchange_api#89]
According to https://github.com/coinexcom/coinex_exchange_api/wiki/012security_authorization, the string `access_id=4DA36FFC61334695A66F8D29020EB589&amount=1.0&market=BTCBCH&price=680&tonce=1513746038205&type=buy&secret_key=B51068CF10B34E7789C374AB932696A05E0A629BE7BFC62F` should produce md5 hash `C6F0DDA352101C2258F992A277397F4A`, but actually the string produces `610AB90A1D31D45901D173E4F59C9384`

Is there something missing in the example?

**Comment by pawn9527** [comment]
> According to https://github.com/coinexcom/coinex_exchange_api/wiki/012security_authorization, the string `access_id=4DA36FFC61334695A66F8D29020EB589&amount=1.0&market=BTCBCH&price=680&tonce=1513746038205&type=buy&secret_key=B51068CF10B34E7789C374AB932696A05E0A629BE7BFC62F` should produce md5 hash `C6F0DDA352101C2258F992A277397F4A`, but actually the string produces `610AB90A1D31D45901D173E4F59C9384`
> 
> Is there something missing in the example?

You are right, we will revise it as soon as possible.
