### ISSUE TITLE
k line ws api is returning message: 'invalid argument'

### ISSUE THREAD

**Issue by Placid7** [coinexcom/coinex_exchange_api#9]
Using the example in the WS API instruction the K line api is returning 'invalid argument'.

{"method":"kline.query","params":["BTCBCH",60],"id": 15}

Market Depth and Latest transaction don't seem to have any issue.

**Comment by Placid7** [comment]
Actually the instruction specify '"id": 5'. I update and still returning same error. So I removed the "id" field all together and the error isn't present. So the "id" field would appear to be what is causing me pain. 

What is the "id" field and what is the correct code for K line. Additionally do you have an updated list of all the "id" and what they are?

**Comment by haipome** [comment]
You must specify the "id", it will send back to you. Because the websocket protocol allow multiple request on one connection, you need use the "id" to mark you request.
