### ISSUE TITLE
Cant do internal withdraw using api..

### ISSUE THREAD

**Issue by flaviomartil** [coinexcom/coinex_exchange_api#91]
On documentations i see -- Inter-user  like a option to not use onchain .. when try it i got:
invalid enum: 'Inter-user'"}

**Comment by flaviomartil** [comment]
its enum field,need the right field, and why its not on docs.

**Comment by flaviomartil** [comment]
{"code": 2, "data": {}, "message": "invalid enum: 'Inter-user'"}

**Comment by versionzhang** [comment]
onchain : Normal transfer 
local: internal withdraw 
You can use "local" for internal withdraw.

**Comment by flaviomartil** [comment]
> onchain : Normal transfer
> local: internal withdraw
> You can use "local" for internal withdraw.
Ok it works. About  coin_adress i tried my personal email and dont worked too.
Can you give me one example? this doc is such a mess to be honest.

**Comment by versionzhang** [comment]
> > onchain : Normal transfer
> > local: internal withdraw
> > You can use "local" for internal withdraw.
> > Ok it works. About  coin_adress i tried my personal email and dont worked too.
> > Can you give me one example? this doc is such a mess to be honest.

You need add one record in Withdrawal Whitelist(under Api management) for using this withdraw api.
We are working on improving this api doc because it's too old and has some errors.

**Comment by flaviomartil** [comment]
happy to know, i got some difficulty to understand some things.. 
About withdraw, i wish i can have a confirmation by email if i want each transation done..
But whitelist for the moment is working
Thank you problem solved.
Please put in docs this new information,will help all developers thank you again.
